<?php

/**
 * implementation of hook_menu
 */
function ktccustom_menu() {

    $items['document/%'] = array(
        'title' => 'Document',
        'page callback' => 'ktc_get_document',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['document-browse'] = array(
        'title' => 'Documents',
        'page callback' => 'ktc_document_browse',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    
    $items['document-browse/%'] = array(
        'title' => 'Documents',
        'page callback' => 'ktc_document_browse_category',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    
    return $items;
}


// gets the file url for the node and sends the user to it
function ktc_get_document($nid) {
    $node = node_load($nid);
    if ($node == NULL) {
        return "There is no document with id " . $nid . ".";
    }
    if (!isset($node->field_document_file['und'])) {
        return "The file associated with this document appears to be missing.";
    }
    $file = file_load($node->field_document_file['und'][0]['fid']);
    //$headers = file_get_content_headers($file);
    //file_transfer($file->uri, $headers);
    $url = file_create_url($file->uri);
    drupal_goto($url);
}


function ktc_document_browse() {
    $topics = taxonomy_get_tree(2);
    $audience = taxonomy_get_tree(3);
    $resourcetypes = taxonomy_get_tree(4); 
    //dpm($topics);
    $rend = array(
        'topics' => $topics,
        'audience' => $audience,
        'resourcetypes' => $resourcetypes,
        '#theme' => 'document_browse',
    );
    return $rend;
}


function ktc_document_browse_category($tid) {
    dpm('adding css');
    drupal_add_css(drupal_get_path('module', 'ktccustom') . '/css/ktccustom.css');
    $topics = taxonomy_get_tree(2);
    $audience = taxonomy_get_tree(3);
    $resourcetypes = taxonomy_get_tree(4); 
    //dpm($topics);
    
    // get docs that match the criteria
    $docs = views_embed_view('documents_by_category', 'block', $tid);
    
    $rend = array(
        'topics' => $topics,
        'audience' => $audience,
        'resourcetypes' => $resourcetypes,
        'docs' => $docs,
        '#theme' => 'document_browse',
    );
    return $rend;
}


function ktccustom_theme() {
  $items = array(
    'document_browse' => array(
      'render element' => 'element',
      'template' => 'tmpl/document-browse',
    ),
  );

  return $items;
}


// examples for the confusing new render system

//t('theme for an element') => array(
//      'child' => array(
//        t('This is some text that should be put together'),
//        t('This is some more text that we need'),
//      ),
//      '#separator' => ' | ',  // Made up for this theme function.
//      '#theme' => 'render_example_aggregate',
//    ),

//function theme_render_example_aggregate($variables) {
//  $output = '';
//  foreach (element_children($variables['element']['child']) as $item) {
//    $output .= $variables['element']['child'][$item] . $variables['element']['#separator'];
//  }
//  return $output;
//}